# 基础配置
title: nikumarugames
description: 你的个人主页
baseurl: ""
url: "https://nikumarugames.io"

# 社交链接
social:
  github: yourusername
  linkedin: yourlinkedin
  twitter: yourtwitter
  email: your@email.com

# 主题设置
theme: jekyll-theme-cayman

# 部署配置
destination: ./
plugins_dir: ./_plugins
build_dir: ./_site

# 添加以下配置确保兼容GitHub Pages
github: [metadata]
plugins:
 - jekyll-feed
 - jekyll-seo-tag 